---
- name: Instalar pacotes base
  apt:
    name:
      - build-essential
      - curl
      - wget
      - git
      - jq
      - htop
      - unzip
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"
